language: node_js

node_js:
  - 7
  - 6
  - 5

script:
  - npm run test
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email: false

after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
